name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: "[${{matrix.otp}}/${{matrix.elixir}}] CI Tests on insta_mealie [OTP/Elixir]"
    runs-on: ubuntu-latest
    env:
      FORCE_COLOR: 1
      MIX_ENV: test
    strategy:
      matrix:
        otp: ["28"]
        elixir: ["1.20.3"]

    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}
      - uses: actions/cache@v4
        with:
          path: deps
          key: ${{ runner.os }}-mix-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
          restore-keys: |
            ${{ runner.os }}-mix-
      - run: mix deps.get
      - run: mix deps.compile
      - run: mix format --check-formatted
      - run: mix compile --warnings-as-errors
      - run: mix credo
      - run: mix doctor --summary
      - run: mix sobelow
      - run: mix coveralls